language: php

php:
  - 8.0.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer install --dev --no-interaction
  - composer require scrutinizer/ocular --no-interaction

script:
  - composer test -- --coverage-clover=build/logs/clover.xml

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
